version: "3"

volumes:
  mysqlVolume:
    external: true
    name: mysqlVolume

services:
  mysql:
    volumes:
      - mysqlVolume:/var/lib/mysql
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
